### ISSUE TITLE
Resume Personal Salesmen

### ISSUE THREAD

**Issue by DredsmanGT** [NKoonen/personalsalesmen#1]
Hello.
Is there a possibility to resume this project for version 8.1.xx of Prestashop?
I have many customers who a need this solution.  

Thanks 
Dredsman

**Comment by NKoonen** [comment]
Hi Dresman,

I have developed this module for other paying customers. I work on a hourly rate, and when i've made an update i share it for free. So if you would like i could send a quotation to update the module for Prestashop 8.

**Comment by DredsmanGT** [comment]
Hi Nkoonen, Please send me a quotation to update module for Prestashop 8.10 / PHP 8.1Best regards, DredsmanEm 4 de jan. de 2024 11:31, Inform-All ***@***.***> escreveu:
Hi Dresman,
I have developed this module for other paying customers. I work on a hourly rate, and when i've made an update i share it for free. So if you would like i could send a quotation to update the module for Prestashop 8.

**Comment by NKoonen** [comment]
Hi please send me a email to info@inform-all.nl so i can send a quotation.

**Comment by NKoonen** [comment]
Update request handled through email.
